### PR TITLE
bump php-http packages dependencies

### PR DESCRIPTION
**Pull request by godbout**
hopefully works. no tests to run!

### CODE REVIEW

**Comment by godbout** [comment]
oh. didn't see a `tests` folder so i assumed there were none but the ci is running. cool.

**Review by jdecool — APPROVED** [review]

**Comment by jdecool** [comment]
Thanks for you PR.

Look good to me :+1: 

There's no test, I need to work on it :)

**Comment by godbout** [comment]
hey thanks for accepting!

you need somehow to bump your package version number though, else we can't grab the new constraints :))

**Comment by jdecool** [comment]
Not sure to understand what you want I do

**Comment by godbout** [comment]
your 0.1.0 still points to the old composer.json. so people who use your package cannot yet have access to the changes made in the PR.

as you're at 0.1.0 probably a switch to 0.2.0 is good enough. so that people (like me) who need the new dependencies, we can require with `^0.2`. does that make sense?

**Comment by godbout** [comment]
in short: you need to tag a new version :D

**Comment by jdecool** [comment]
Yeah it's planned :)

I will do it after the weekend

**Comment by godbout** [comment]
great. thanks! looking forward to be able to use your package.

**Pull request merged**
